require('core.plugin_config.neotree')
require('core.plugin_config.catppuccin')
require('core.plugin_config.lualine')
require('core.plugin_config.colorizer')
require('core.plugin_config.gitsigns')
require('core.plugin_config.bufferline')
