require('core.plugin_config.lazy')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.colorizer')
require('core.plugin_config.autopairs')
require('core.plugin_config.lualine')
